"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { ShieldAlert, KeyRound, RefreshCw } from "lucide-react";
import CyberParticles from "@/components/CyberParticles";
import { useSim } from "@/context/SimContext";

export default function MfaPage() {
  const router = useRouter();
  const { currentUser, verifyMfa } = useSim();
  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [timeLeft, setTimeLeft] = useState(30);
  const [mockToken, setMockToken] = useState("482 915");

  // Timer simulating Google Authenticator rolling codes every 30s
  useEffect(() => {
    const interval = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          // Generate new mock token
          const part1 = Math.floor(100 + Math.random() * 900);
          const part2 = Math.floor(100 + Math.random() * 900);
          setMockToken(`${part1} ${part2}`);
          return 30;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault();
    const sanitised = code.replace(/\s+/g, "");
    
    if (sanitised.length !== 6) {
      setError("MFA authentication code must be 6 digits.");
      return;
    }

    const success = verifyMfa(sanitised);
    if (success) {
      // Determine dashboard routes based on user role
      if (currentUser?.role === "Employee") {
        router.push("/portal");
      } else {
        router.push("/dashboard/soc");
      }
    } else {
      setError("Invalid security verification code. Please check your token device.");
    }
  };

  const handleAutoFill = () => {
    const raw = mockToken.replace(/\s+/g, "");
    setCode(raw);
    setError("");
  };

  return (
    <div className="relative min-h-screen bg-[#020205] flex items-center justify-center p-6 overflow-hidden font-sans">
      
      {/* Cyber Particles background */}
      <CyberParticles />
      
      <div className="cyber-grid absolute inset-0 z-0"></div>
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[350px] h-[350px] bg-primary/5 rounded-full blur-[120px] pointer-events-none"></div>

      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.4 }}
        className="relative z-10 w-full max-w-md text-left"
      >
        <div className="flex flex-col items-center mb-8">
          <div className="w-12 h-12 rounded-xl bg-gradient-to-tr from-primary to-secondary p-[1px] flex items-center justify-center shadow-[0_0_20px_rgba(0,240,255,0.3)] mb-4">
            <div className="w-full h-full bg-slate-950 rounded-xl flex items-center justify-center">
              <ShieldAlert className="w-6 h-6 text-primary" />
            </div>
          </div>
          <h2 className="font-outfit text-2xl font-black tracking-widest text-slate-100 text-glow-primary">
            MFA VERIFICATION
          </h2>
          <p className="text-xs text-slate-500 font-mono tracking-wider mt-1 uppercase">
            MULTI-FACTOR SECURITY CHALLENGE
          </p>
        </div>

        <div className="cyber-card p-8 rounded-xl border border-slate-900 bg-slate-950/60 backdrop-blur-md shadow-2xl">
          <h3 className="font-outfit text-lg font-bold text-slate-100 mb-2 flex items-center gap-2">
            <span className="w-1 h-3.5 bg-primary rounded-full shadow-[0_0_8px_var(--primary)]"></span>
            ENTER VERIFICATION CODE
          </h3>
          <p className="text-xs text-slate-400 font-medium mb-6">
            Input the 6-digit verification code generated by your corporate authentication application.
          </p>

          {error && (
            <div className="bg-red-950/40 border border-red-900/60 text-red-400 text-xs p-3 rounded mb-4 font-mono">
              [ERROR] {error}
            </div>
          )}

          {/* Simulated token box */}
          <div className="border border-slate-900 bg-slate-950/90 rounded-lg p-4 mb-6 text-center select-none relative overflow-hidden">
            <span className="text-[10px] text-slate-500 block font-mono font-bold tracking-widest mb-1.5">SIMULATED MFA DEVICE</span>
            <div className="flex justify-between items-center px-4">
              <span className="font-outfit text-3xl font-extrabold text-primary tracking-widest font-mono">
                {mockToken}
              </span>
              <div className="flex items-center gap-1.5 font-mono text-[10px] text-slate-500 font-bold">
                <RefreshCw className="w-3.5 h-3.5 text-primary animate-spin" style={{ animationDuration: "10s" }} />
                <span>{timeLeft}s</span>
              </div>
            </div>
            {/* Quick-fill helper link */}
            <button
              onClick={handleAutoFill}
              className="mt-3 text-[9px] font-mono font-extrabold tracking-wider text-accent border border-accent/20 bg-accent/5 px-3 py-1 rounded hover:bg-accent hover:text-slate-950 transition-colors w-full cursor-pointer"
            >
              AUTO-FILL WITH THIS TOKEN
            </button>
          </div>

          <form onSubmit={handleVerify} className="space-y-5">
            <div>
              <label className="block text-[10px] font-mono text-slate-400 font-bold uppercase mb-1.5 tracking-wider">
                6-DIGIT CODE
              </label>
              <div className="relative">
                <KeyRound className="absolute left-3 top-3 w-4.5 h-4.5 text-slate-500" />
                <input
                  type="text"
                  placeholder="000000"
                  maxLength={6}
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/[^0-9]/g, ""))}
                  className="w-full bg-[#04040c]/80 border border-slate-800 focus:border-primary/50 text-slate-200 pl-10 pr-4 py-2.5 rounded text-sm outline-none transition-colors font-mono tracking-widest text-center text-lg font-bold"
                  required
                />
              </div>
            </div>

            <button
              type="submit"
              className="cyber-btn w-full py-3 rounded text-xs tracking-widest font-mono text-center flex items-center justify-center cursor-pointer shadow-[0_0_15px_rgba(0,240,255,0.08)]"
            >
              VERIFY CREDENTIALS
            </button>
          </form>
        </div>

        <div className="text-center text-[10px] font-mono text-slate-600 mt-6">
          <span>ANY 6-DIGIT CODE WILL PASS IN DEMO MODE</span>
        </div>
      </motion.div>
    </div>
  );
}
